name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 12 * * *"}]
  # Run workflow manually
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer, scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
        
    
      - name: GitHub
        uses: lowlighter/metrics@latest
        with:
          config_timezone: America/Sao_Paulo
          token: ${{ secrets.METRICS_TOKEN }}
          
      - name: Spotify - Top Artists
        uses: lowlighter/metrics@latest
        with:
          filename: spotify.topartists.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: long
          plugin_music_top_type: artists
